### ISSUE TITLE
Editor.ReloadFile.lua - варнинг W211 выводимыq LuaCheck 0.18

### ISSUE THREAD

**Issue by VictorVG** [ildar-shaimordanov/tea-set#1]
В строке 17 LuaCheсk справедливо выводит варнинг W211 - объявление неиспользуемой переменной l`ocal MSG_YESNO    = 0x00040000` . Можно её закометировать, можно убрать, а можно радоваться картинке:

![w211](https://cloud.githubusercontent.com/assets/906886/22126875/9330495e-deaa-11e6-8da6-dae2c68913d5.png)

- я предпочёл убрать за ненужностью.:)

**Comment by ildar-shaimordanov** [comment]
Все верно. Это неиспользуемая переменная. .Спасибо, что напомнили.

**Comment by ildar-shaimordanov** [comment]
fixed in commit cb2950e

**Comment by VictorVG** [comment]
Не за что. Кстати и пустое поле Flags="" лишнее. Можно смело убрать за ненужностью. Главное при сохранении убирать концевые пробелы - если они есть на них сразу LuaCheck старших версий  выводит варнинг. Чтобы самому не возится с подбором модулей и правкой доки можно у меня его взять вместе с документацией (обновляю архив по мере выхода обновлений пакета и доков к нему, ссылка постоянная) [**LuaCheck_working.7z**](https://yadi.sk/d/ATfB92h6hKEaE) . 

 Я тут с иным явлением столкнулся - если в конфигах скрипта LuaManager написанным Игорем нет параметра PatchFilter или он содержит некорректное значение - править намучаешься ибо иной раз и сам скрипт может наделать проблем. Какой час вожусь с правками, а по идее-то если переменная пустая, то просто считывать переменную %FARPROFILE%, разворачивать и подставлять значения. А ещё лучше сразу через неё работать...
